name: CI/CD Corte Fácil

on:
  push:
    branches: [auth]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Instalar dependências backend
        run: |
          cd backend
          npm install
      - name: Rodar testes backend
        run: |
          cd backend
          npm test

  test-frontend:
    runs-on: ubuntu-latest
    needs: test-backend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Instalar dependências frontend
        run: |
          cd frontend
          npm install
      - name: Rodar testes frontend
        run: |
          cd frontend
          npm test
