name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Cache dependencies
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Backend
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install

    - name: Run Backend Tests
      run: |
        cd backend
        npm test
      env:
        DB_URI: ${{ secrets.DB_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        NODE_ENV: 'test'

    # Frontend
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install

    - name: Build Frontend
      run: |
        cd frontend
        npm run build
      env:
        CI: false
        REACT_APP_API_URL: 'https://cortefacil-chat-6b9c1276ad86.herokuapp.com/api'

    # Deploy Backend to Heroku
    - name: Deploy Backend to Heroku
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "cortefacil-chat-6b9c1276ad86"
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: "backend"
      env:
        HD_DB_URI: ${{ secrets.DB_URI }}
        HD_JWT_SECRET: ${{ secrets.JWT_SECRET }}
        HD_NODE_ENV: 'production'

    # Deploy Frontend to Vercel
    - name: Deploy Frontend to Vercel
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./frontend
        vercel-args: '--prod' 